### ISSUE TITLE
Service does not respond when regex matched line occurs at the beginning of a gig long file

### ISSUE THREAD

**Issue by Kaustubh-cribl** [dleemath/cribl-takehome#2]
Service does not respond when regex matched line occurs at the beginning of a gig long file

Acceptance criteria:

1. Service should respond correctly for all use cases

<img width="382" alt="Screenshot 2024-06-24 at 10 21 57 PM" src="https://github.com/dleemath/cribl-takehome/assets/171298919/9939d63b-7045-4d1e-b6ed-f3f5ec7461a6">

<img width="867" alt="Screenshot 2024-06-24 at 10 19 28 PM" src="https://github.com/dleemath/cribl-takehome/assets/171298919/28ff3aec-7438-449b-863a-15cd45fb95fe">
 
<img width="1409" alt="Screenshot 2024-06-24 at 10 20 24 PM" src="https://github.com/dleemath/cribl-takehome/assets/171298919/5472ad61-4dd1-46e5-a558-c740aa93b336">

**Comment by dleemath** [comment]
This is because the line size is bigger than the buffer chunk size, we may increase the buffer size to 10 MB e.g. 
```
  1 class Config(object):
  2     TESTING = False
  3     DEFAULT_PAGE_SIZE = 1000
  4     DEFAULT_RESPONSE_LINES_SIZE = 1000
  5     DEFAULT_CHUNK_SIZE = 1024 * 1024 * 10
  ```
  
  test:
  
  tail -n 1 install.log |wc -m
  
  ```
  powered onPCGPCJ6NXW softwareupdated[82775]: SUOSUPowerEventObserver: System has powered onPCGPCJ6NXW softwareupdated[82775]: SUOSUPowerEventObserver: System has powered onPCGPCJ6NXW softwareupdated[82775]: SUOSUPowerEventObserver: System has powered onPCGPCJ6NXW softwareupdated[82775]: SUOSUPowerEventObserver: System has powered onPCGPCJ6NXW softwareupdated[82775]: SUOSUPowerEventObserver: System has powered onPCGPCJ6NXW softwareupdated[82775]: SUOSUPowerEventObserver: System has powered onPCGPCJ6NXW softwareupdated[82775]: SUOSUPowerEventObserver: System has powered onPCGPCJ6NXW softwareupdated[82775]: SUOSUPowerEventObserver: System has powered",
        "2024-06-24 22:34:21-07 PCGPCJ6NXW softwareupdated[82775]: SUOSUPowerEventObserver: System will power on"
    ],
    "metadata": {
        "lines_retrieved": 2,
        "next_request": null
    }
  ```

**Comment by dleemath** [comment]
default chunk size increase to 10mb
